const SET_LOGUED_ACCOUNT = 'SET_LOGUED_ACCOUNT';

const SET_DESTINATIONS = 'SET_DESTINATIONS';

const SET_VOUCHERS = 'SET_VOUCHERS';

const SET_SURVEYS = 'SET_SURVEYS';

const UPDATE_DESTINATION = 'UPDATE_DESTINATION';

export { SET_LOGUED_ACCOUNT, SET_DESTINATIONS, SET_VOUCHERS, UPDATE_DESTINATION, SET_SURVEYS };