const SET_LOGUED_ACCOUNT = 'SET_LOGUED_ACCOUNT';

const SET_DESTINATIONS = 'SET_DESTINATIONS';

const UPDATE_DESTINATION = 'UPDATE_DESTINATION';

export { SET_LOGUED_ACCOUNT, SET_DESTINATIONS, UPDATE_DESTINATION };